#!/usr/bin/env node

/**
 * Automated Icon Generation Script
 * 
 * Converts SVG files from assets/icons/ into React Native components
 * with TypeScript support and NativeWind integration.
 * 
 * Usage: npm run icons:generate
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ASSETS_DIR = path.join(__dirname, '..', 'assets', 'icons');
const OUTPUT_DIR = path.join(__dirname, '..', 'src', 'components', 'icons');

console.log('🎨 Starting automated icon generation...\n');

// Step 1: Check if assets/icons directory exists
if (!fs.existsSync(ASSETS_DIR)) {
  console.error(`❌ Error: Directory ${ASSETS_DIR} does not exist!`);
  console.log('\n📝 Please create assets/icons/ and add your SVG files there.\n');
  process.exit(1);
}

// Step 2: Check if there are SVG files
const svgFiles = fs.readdirSync(ASSETS_DIR).filter(file => file.endsWith('.svg'));

if (svgFiles.length === 0) {
  console.error(`❌ Error: No SVG files found in ${ASSETS_DIR}`);
  console.log('\n📝 Please add .svg files to assets/icons/ directory.\n');
  process.exit(1);
}

console.log(`✅ Found ${svgFiles.length} SVG file(s):\n`);
svgFiles.forEach((file, index) => {
  console.log(`   ${index + 1}. ${file}`);
});
console.log('');

// Step 3: Create output directory if it doesn't exist
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  console.log(`✅ Created output directory: ${OUTPUT_DIR}\n`);
}

// Step 4: Run SVGR to generate components
try {
  console.log('🔄 Generating React Native components...\n');
  
  execSync(
    `npx @svgr/cli --config-file=svgr.config.js --out-dir=${OUTPUT_DIR} ${ASSETS_DIR}`,
    { stdio: 'inherit' }
  );
  
  console.log('\n✅ Components generated successfully!\n');
} catch (error) {
  console.error('❌ Error generating components:', error.message);
  process.exit(1);
}

// Step 5: Generate index.ts file
console.log('📝 Generating index.ts...\n');

try {
  const componentFiles = fs
    .readdirSync(OUTPUT_DIR)
    .filter(file => file.endsWith('.tsx') && file !== 'index.ts');

  const exports = componentFiles
    .map(file => {
      const componentName = path.basename(file, '.tsx');
      return `export { default as ${componentName} } from './${componentName}';`;
    })
    .join('\n');

  const indexContent = `/**
 * Auto-generated icon exports
 * 
 * Generated by: npm run icons:generate
 * Do not edit this file manually!
 */

${exports}\n`;

  fs.writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), indexContent);
  
  console.log(`✅ Generated index.ts with ${componentFiles.length} exports\n`);
} catch (error) {
  console.error('❌ Error generating index.ts:', error.message);
  process.exit(1);
}

// Step 6: Success summary
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('🎉 Icon generation completed successfully!');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
console.log('📁 Output directory:', OUTPUT_DIR);
console.log('📦 Components generated:', svgFiles.length);
console.log('\n📚 Usage example:\n');
console.log('   import { HomeIcon, ProfileIcon } from \'@/components/icons\';\n');
console.log('   <HomeIcon size={24} color="#009FE3" />\n');
